<?php
	$sql="create table if not exists gt_protables(`id` int not null auto_increment primary key comment '唯一自增id',`date` int(20) not null comment '填表日期',`author` varchar(10) not null comment '填表人',`customer_a` varchar(20) not null comment '客户单位',`customer_b` varchar(10) not null comment '客户姓名',`salesman` varchar(10) not null comment '业务负责人',`mdate` int(20) not null comment '我方签字日期',`ydate` int(20) not null comment '客户签字日期',`cdate` int(20) not null comment '合同签订日期',`aom` int(10) not null comment '合同金额',`paytype` varchar(20) not null comment '付款方式',`cnum` int(20) not null comment '合同编号',`onum` int(20) not null comment '下单编号',`prjman` varchar(10) not null comment '项目负责人',`odate` varchar(20) not null comment '下单日期',`sdate` varchar(20) not null comment '发货日期',`stype` varchar(20) not null comment '发货方式',`techman` varchar(10) not null comment '安装调试人',`tdate` varchar(20) not null comment '安装日期',`checkdate` varchar(20) not null comment '验货日期',`checkman` varchar(10) not null comment '验收人',`cpu` varchar(20) not null comment 'CPU',`memery` varchar(20) not null comment '内存',`board` varchar(20) not null comment '主板',`other` varchar(50) not null comment '其他配件',`kdate` varchar(20) not null comment '开票日期',`kom` int(10) not null comment '开票金额',`vtax` int(10) not null comment '增值税额',`othertax` int(10) not null comment '其他>税额',`salescost` int(10) not null comment '售前成本',`sentcost` int(10) not null comment '送货成本',`mancost` int(10) not null comment '人力成本',`cost` int(10) not null comment '总成本',`gdate` varchar(20) not null comment '付款日期',`gom` int(10) not null comment '付款金额',`shom` int(10) not null comment '应收账款',`subdate` int(20) not null comment '提交日期',`htstatus` int(1) not null default 0 comment '合同状态',`xdstatus` int(1) not null default 0,`fhstatus` int(1) not null default 0,`kpstatus` int(1) not null default 0,`skstatus` int(1) not null default 0,`showstatus` int(1) NOT NULL DEFAULT '0' COMMENT '显示状态')engine=myisam default charset=utf8;";
	$reust = mysql_query($sql);
	if(!$reust){
		die('error:'.mysql_error());
	}else{
		die('successs!');
	}
?>
